name: CI
on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install system-level dependencies (for pycairo/reportlab)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libfreetype6-dev pkg-config python3-dev

      # Step 4: Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Simple lint/test placeholder
      - name: Run lint (simple)
        run: |
          echo "Sanity check- backend environment successfully built"
